import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Fake Bank</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquid culpa cupiditate dignissimos dolore ducimus ea ex expedita fuga id ipsum maiores, nisi numquam possimus quae quaerat quam quis, reprehenderit suscipit tempora voluptatibus! Amet aspernatur at autem beatae consequatur, cum cumque delectus dignissimos dolore ducimus eos facere facilis fugit impedit ipsa itaque libero modi molestias mollitia necessitatibus nostrum odit officia perferendis porro quia recusandae tempora veritatis? Ea ipsam temporibus vel! A at dolor dolorum earum illo rem sed sequi ut, vel veritatis! Asperiores corporis debitis eligendi eos esse est facilis, fugiat hic id in incidunt iure laboriosam laudantium magnam molestias obcaecati officia officiis provident quae quasi quisquam saepe sapiente sed, temporibus totam vero voluptatibus. Aperiam excepturi, ullam. A assumenda consectetur ipsam nesciunt nulla, pariatur quisquam sit unde. Enim, illum, omnis! Assumenda consequuntur corporis culpa deserunt dicta doloremque eaque error ex expedita explicabo facere fuga nam nisi, perferendis quam velit, veritatis! Eius eos ex modi mollitia nihil odio odit quaerat qui! Amet cumque dolore eaque eligendi eum ex exercitationem illo iste iusto minima odit omnis pariatur quas quisquam quod, quos reiciendis sapiente veritatis. Ab aliquid est iste perferendis repudiandae sequi ullam. Ad, cumque earum et iste laudantium modi porro quo reiciendis voluptates.
        </p>
      </main>
    </div>
  )
}
